// Auto-generated bar type categorization for auto-calculation
// Generated from Excel formula analysis

/**
 * Full Span bar types - Simple pattern with beam penetrations
 * Formula: a=Span, b=Beam-Cover, c=Beam-Cover, d=Depth-2*Cover, e=Depth-2*Cover
 */
const FULL_SPAN_TYPES = new Set([
  "Bottom Bar (X-X) Full Span",
  "Bottom Bar (Y-Y) Full Span",
  "Bottom Bar (Y-Y) Full Span (C8 To C9)",
  "Bottom Bar (Y-Y) Full Span C5 to C4",
  "Top Bar (X-X) Full Span",
  "Top Bar (Y-Y) Full Span",
]);

/**
 * Distribution bar types - Perpendicular span pattern
 * Formula: a=Perp Span, b=Beam-Cover, c=Beam-Cover, d=95, e=95
 */
const DISTRIBUTION_TYPES = new Set([
  "Bottom Bar Dist (X-X)",
  "Bottom Bar Dist (Y-Y)",
  "Top Bar Dist (Y-Y)",
  "Top Dist Bar (X-X)",
  "Top Dist Bar (X-X) - A2 only",
  "Top Dist Bar (X-X) - A3 only",
  "Top Dist Bar (X-X) - A7 only",
  "Top Dist Bar (X-X) - B1 only & A2 link",
  "Top Dist Bar (X-X) - B2 only",
  "Top Dist Bar (X-X) - B6 only",
  "Top Dist Bar (X-X) - B6 to D7",
  "Top Dist Bar (X-X) - C2 to D1",
  "Top Dist Bar (X-X) - E5 only",
  "Top Dist Bar (X-X) - Left",
  "Top Dist Bar (X-X) - Left & Right",
  "Top Dist Bar (X-X) - Left G5 to H3",
  "Top Dist Bar (X-X) - Left K1 to L1",
  "Top Dist Bar (X-X) - Left M5 to N5",
  "Top Dist Bar (X-X) - Right",
  "Top Dist Bar (X-X) -C2 link",
  "Top Dist Bar (Y-Y) - A2 only upto 1225",
  "Top Dist Bar (Y-Y) - A2 only upto 1225 (Top & Bottom)",
  "Top Dist Bar (Y-Y) - A2 only upto 2835",
  "Top Dist Bar (Y-Y) - A5 only",
  "Top Dist Bar (Y-Y) - B2 only",
  "Top Dist Bar (Y-Y) - Bottom",
  "Top Dist Bar (Y-Y) - C8 to C9",
  "Top Dist Bar (Y-Y) - C9 only",
  "Top Dist Bar (Y-Y) - C9 to D7",
  "Top Dist Bar (Y-Y) - D0 only",
  "Top Dist Bar (Y-Y) - D2 to E1",
  "Top Dist Bar (Y-Y) - D6 only",
  "Top Dist Bar (Y-Y) - G1 only",
  "Top Dist Bar (Y-Y) - G4 only",
  "Top Dist Bar (Y-Y) - G4 to G5",
  "Top Dist Bar (Y-Y) - I4 only",
  "Top Dist Bar (Y-Y) - J1 only",
  "Top Dist Bar (Y-Y) - K4 only",
  "Top Dist Bar (Y-Y) - K5 only",
  "Top Dist Bar (Y-Y) - M1 only",
  "Top Dist Bar (Y-Y) - O4 only",
  "Top Dist Bar (Y-Y) - O5 only",
  "Top Dist Bar (Y-Y) - P1 only",
  "Top Dist Bar (Y-Y) - Q8 only",
  "Top Dist Bar (Y-Y) - Short Segment only",
  "Top Dist Bar (Y-Y) - Top",
  "Top Dist Bar (Y-Y) - Top & Bottom",
  "Top Dist Bar (Y-Y) - Top & Bottom (A7 Link)",
  "Top Dist Bar (Y-Y) - Top & Bottom D2 only",
  "Top Dist Bar (Y-Y) - Top (B1 only)",
  "Top Dist Bar (Y-Y) - Top (B3 only)",
  "Top Dist Bar (Y-Y) - Top A7 only",
  "Top Dist Bar (Y-Y) - Top C2 only",
  "Top Dist Bar (Y-Y) - Top C7 only",
  "Top Dist Bar (Y-Y) - Top D1 only",
  "Top Dist Bar (Y-Y) -K5 only",
  "Top Dist Bar (Y-Y) -O5 only",
  "Top Dist Bar (Y-Y) -Q8 only",
  "Top Dist Bar (Y-Y) -Top & Bottom",
  "Top Dist Bar (Y-Y) -Top L1 to L2",
  "Top DistBar (Y-Y) - Bottom (Lift)",
]);

/**
 * Combined bar types (Bottom & Top)
 * Formula: Similar to U-Bar but different field mapping
 */
const COMBINED_TYPES = new Set([
  "Bottom & Top Bar (X-X)",
  "Bottom & Top Bar (Y-Y)",
  "Top & Bottom Bar (Y-Y)",
  "Top Main Bar (X-X) - Left & Right",
  "Top MainBar (X-X) - Left & Right",
  "Top MainBar (Y-Y) - Top & Bottom",
  "Top MainBar (Y-Y) -Top & Bottom",
]);

/**
 * U-Bar types - Complex pattern with top extensions
 * Formula: a=Span, b=2*(Beam-Cover), c=2*(Beam-Cover) or 4*(Depth-2*Cover), d=Depth-2*Cover, e=Depth-2*Cover, f=Extensions
 */
const U_BAR_TYPES = new Set([
  "Bottom Bar (X-X)",
  "Bottom Bar (X-X) G2 to I2",
  "Bottom Bar (X-X) Right Segment",
  "Bottom Bar (Y-Y)",
  "Bottom Bar (Y-Y) I3 to C4",
  "Bottom Bar (Y-Y) O3 to C4",
  "Bottom Bar (Y-Y) upto 2550",
  "Bottom Bar (Y-Y) upto 3650",
  "Top Bar (X -X) N1 to O2",
  "Top Bar (X-X)",
  "Top Bar (X-X) K2 to C4",
  "Top Bar (X-X) Q2 to C4",
  "Top Bar (Y-Y)",
  "Top Bar (Y-Y) F2 to C4",
  "Top Bar (Y-Y) K4 to K5",
  "Top Bar (Y-Y) Q6 to Q8",
  "Top Bar Main (Y-Y) Q1 to Q2",
  "Top Bar Main (Y-Y) Q5 to Q7",
  "Top Main Bar (X-X) - G5 to H3",
  "Top Main Bar (X-X) - H1 to I2",
  "Top Main Bar (X-X) - H3 to I4",
  "Top Main Bar (X-X) - I1 to J1",
  "Top Main Bar (X-X) - I4 to J5",
  "Top Main Bar (X-X) - J1 to K1",
  "Top Main Bar (X-X) - J2 to L2",
  "Top Main Bar (X-X) - J4 to K4",
  "Top Main Bar (X-X) - J5 to K5",
  "Top Main Bar (X-X) - K5 to M5",
  "Top Main Bar (X-X) - L1 to M1",
  "Top Main Bar (X-X) - Left K1 to L1",
  "Top Main Bar (X-X) - M1 to O1",
  "Top Main Bar (X-X) - M4 to N4",
  "Top Main Bar (X-X) - M5 to N5",
  "Top Main Bar (X-X) - N4 to O4",
  "Top Main Bar (X-X) - O1 to P1",
  "Top Main Bar (X-X) - P1 to Q1",
  "Top Main Bar (X-X) - P4 to Q6",
  "Top Main Bar (X-X) - P5 to Q7",
  "Top Main Bar (X-X) - Right",
  "Top Main Bar (X-X) -O4 to P5",
  "Top Main Bar (Y-Y) - A7 to A8",
  "Top Main Bar (Y-Y) - A7 to A9",
  "Top Main Bar (Y-Y) - Bottom",
  "Top Main Bar (Y-Y) - C2 to C4",
  "Top Main Bar (Y-Y) - C5 to C4",
  "Top Main Bar (Y-Y) - C7 to C9",
  "Top Main Bar (Y-Y) - D1 to D2",
  "Top Main Bar (Y-Y) - Right",
  "Top Main Bar (Y-Y) - Short Segment to A9",
  "Top Main Bar (Y-Y) -Top L1 to L2",
  "Top Main Bar (Y-Y) -Top O1 to O2",
  "Top MainBar (X-X) - A2 to B1",
  "Top MainBar (X-X) - A2 to B2",
  "Top MainBar (X-X) - A3 to B2",
  "Top MainBar (X-X) - A7 to B5",
  "Top MainBar (X-X) - C2 to D1",
  "Top MainBar (X-X) - C2 to D2",
  "Top MainBar (X-X) - E5 to F3",
  "Top MainBar (X-X) - E5 to F4",
  "Top MainBar (X-X) - H2 to J4",
  "Top MainBar (X-X) - I2 to J2",
  "Top MainBar (X-X) - Left",
  "Top MainBar (X-X) - N4 to P4",
  "Top MainBar (X-X) - O2 to P2",
  "Top MainBar (X-X) - Right",
  "Top MainBar (X-X) - Right G1 to I1",
  "Top MainBar (X-X) - Right G2 to I2",
  "Top MainBar (X-X) - Right G4 to H2",
  "Top MainBar (X-X) -A9 to B6",
  "Top MainBar (X-X) -B1 to C2",
  "Top MainBar (X-X) -B2 to C2",
  "Top MainBar (X-X) -B5 to C5",
  "Top MainBar (X-X) -B6 to D7",
  "Top MainBar (X-X) -B7 to C9",
  "Top MainBar (X-X) -Right",
  "Top MainBar (X-X) -Top",
  "Top MainBar (Y-Y) - A2 to A5",
  "Top MainBar (Y-Y) - A5 to B1",
  "Top MainBar (Y-Y) - B1 to A5",
  "Top MainBar (Y-Y) - B1 to B2",
  "Top MainBar (Y-Y) - B1 to B3",
  "Top MainBar (Y-Y) - B3 to B4",
  "Top MainBar (Y-Y) - Bottom",
  "Top MainBar (Y-Y) - Bottom (Lift)",
  "Top MainBar (Y-Y) - Bottom D2 to E1",
  "Top MainBar (Y-Y) - C8 to C9",
  "Top MainBar (Y-Y) - C9 to D7",
  "Top MainBar (Y-Y) - E3 to C4",
  "Top MainBar (Y-Y) - E5 to C4",
  "Top MainBar (Y-Y) - F3 to F4",
  "Top MainBar (Y-Y) - G1 to G2",
  "Top MainBar (Y-Y) - G1 to H1",
  "Top MainBar (Y-Y) - G4 to G5",
  "Top MainBar (Y-Y) - H2 to C4",
  "Top MainBar (Y-Y) - H2 to H3",
  "Top MainBar (Y-Y) - H2 to I4",
  "Top MainBar (Y-Y) - I1 to I2",
  "Top MainBar (Y-Y) - I2 to C4",
  "Top MainBar (Y-Y) - J1 to C4",
  "Top MainBar (Y-Y) - J1 to J2",
  "Top MainBar (Y-Y) - J2 to C4",
  "Top MainBar (Y-Y) - J4 to C4",
  "Top MainBar (Y-Y) - J4 to J5",
  "Top MainBar (Y-Y) - Left",
  "Top MainBar (Y-Y) - M1 to N1",
  "Top MainBar (Y-Y) - M1 to N2",
  "Top MainBar (Y-Y) - M4 to M5",
  "Top MainBar (Y-Y) - N2 to C4",
  "Top MainBar (Y-Y) - N2 to O4",
  "Top MainBar (Y-Y) - N4 to N5",
  "Top MainBar (Y-Y) - N4 to P4",
  "Top MainBar (Y-Y) - O2 to C4",
  "Top MainBar (Y-Y) - P1 to P2",
  "Top MainBar (Y-Y) - P2 to C4",
  "Top MainBar (Y-Y) - P4 to C4",
  "Top MainBar (Y-Y) - P4 to P5",
  "Top MainBar (Y-Y) - Top",
  "Top MainBar (Y-Y) - Top - A9 to A10",
  "Top MainBar (Y-Y) - Top B6 to B7",
  "Top MainBar (Y-Y) - Top D2 to D4",
  "Top MainBar (Y-Y) - Top D2 to E3",
  "Top MainBar (Y-Y) -B5 to B6",
  "Top MainBar (Y-Y) -Bottom",
  "Top MainBar (Y-Y) -I4 to J4",
  "Top MainBar (Y-Y) -J2 to K1",
  "Top MainBar (Y-Y) -K3 to K5",
  "Top MainBar (Y-Y) -K4 to K5",
  "Top MainBar (Y-Y) -N4 to O4",
  "Top MainBar (Y-Y) -O4 to P4",
  "Top MainBar (Y-Y) -P2 to Q1",
  "Top MainBar (Y-Y) -Q6 to Q8",
  "Top MainBar (Y-Y) -Q8 to Q7",
  "Top MainBar (Y-Y) -Top",
  "Top MainBar (Y-Y) -Top D0 to D1",
  "Top MainBar (Y-Y) -Top D6 to D7",
  "Top MainBar (Y-Y) -Top Segment",
]);
